services:
  - type: web
    name: tsunagari
    runtime: ruby
    plan: free
    buildCommand: bundle exec rails assets:precompile
    preDeployCommand: bundle exec rails db:prepare
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: RAILS_MAX_THREADS
        value: "3"
      - key: TSUNAGARI_LIST_REQUEST_STARTER_PAYMENT_URL
        sync: false
      - key: TSUNAGARI_LIST_REQUEST_CURATED_PAYMENT_URL
        sync: false
